### ISSUE TITLE
How in the world do we get access to this and become a Cloud Storage Partner?

### ISSUE THREAD

**Issue by jezell** [Microsoft/Office-Online-Test-Tools-and-Documentation#109]
I can use Google Docs for free. I can use OneDrive for free. I can sign up for Box view and be using it in a few minutes. But I can't even pay for a service from Microsoft with an API to preview their own documents? Why are you so hard to work with?

**Comment by tylerbutler** [comment]
You can apply to the Cloud Storage Partner program here: http://dev.office.com/programs/officecloudstorage

The program has been very popular and we are adding partners as fast as we can.

Issue #70 tracks adding some clarification to these docs about the program and linking to the application form.

**Comment by jezell** [comment]
We applied as soon as it was announced and never received any follow up. :(

**Comment by jezell** [comment]
We wrote all the wopi integration against Office Web Apps server, but would really prefer to use a fully managed environment instead of scaling out some Windows Servers in AWS separate from the rest of our environment, which is non-Windows.
