### ISSUE TITLE
How can I test my local WOPI REST endpoints

### ISSUE THREAD

**Issue by benjaminliugang** [Microsoft/Office-Online-Test-Tools-and-Documentation#110]
If I implement all of the WOPI REST endpoints, how could I specify office online send WOPI request to my local WOPI server? Or I must register a public domain link to my local server, then office online use the public domain connect to my local server.

**Comment by chrisbro-MSFT** [comment]
There are two options right now, and we have a third in progress.

Today, you can either connect your server to the internet using a domain that is in our WOPI allowlist and test through that, perhaps by using the WOPI Validation Service (https://wopi.readthedocs.org/en/latest/build_test_ship/validator.html).  You can also use the on-prem Office Web Apps Server product, but the publicly-available version is several years old and does not have some of the newer WOPI changes, most notably editing support for Word against custom WOPI hosts.

One day we would like to release the WOPI Validator as an open source project here on github.  It will have the core engine to run the tests, a command line tool that wraps the engine, and the test definitions.  Then you can compile it and run the tests against your host locally.  I'm afraid I can't give you an estimate as to when we'll finish that work, though.
