### ISSUE TITLE
Add schema info for test results from validator

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#122]
string Name;
int Status;
IEnumerable<RequestInfoForClient> RequestDetails;
string Message;

**Status** is:
Skipped==0
Passed==1
Failed==2

**RequestInfoForClient** is:
string Name;
string TargetUrl;
Dictionary<string, string> RequestHeaders;
int ResponseStatusCode;
Dictionary<string, string> ResponseHeaders;
string ResponseData;

**Comment by fabiovazquez** [comment]
We've added a new field to the RequestInfoForClient interface: ValidationFailures. The current version of the RequestInfoForClient contract looks like this:

string Name;
string TargetUrl;
Dictionary<string, string> RequestHeaders;
int ResponseStatusCode;
Dictionary<string, string> ResponseHeaders;
string ResponseData;
IEnumerable<String> ValidationFailures;

The new "ValidationFailures" field will contain the validation messages of each individual validator that failed.
