### ISSUE TITLE
Sometimes getting proof key based on %-encoded version of the URL

### ISSUE THREAD

**Issue by yasufs** [Microsoft/Office-Online-Test-Tools-and-Documentation#125]
When WAC calls into our CheckFileInfo REST endpoint, about 0.1% of the time our proof key validation is failing because WAC is sending us proof keys based on a %-encoded version of the URL. Specifically, our file IDs contain the tilde ('~') character, but the proof keys seem to be based on a URL where the tilde has been replaced by the corresponding escape sequence "%7E".

**Comment by chrisbro-MSFT** [comment]
Is this mitigated now that we have the proof key debugging UI in the validator?

**Comment by tylerbutler** [comment]
This hasn't come up in over three years... closing.
