### ISSUE TITLE
Clarify X-WOPI-RelativeTarget and X-WOPI-SuggestedTarget

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#13]
Are X-WOPI-RelativeTarget and X-WOPI-SuggestedTarget mutually exclusive?

**Comment by tylerbutler** [comment]
Questions for @chrisbro-MSFT:

1. Are X-WOPI-RelativeTarget and X-WOPI-SuggestedTarget mutually exclusive?
2. In what scenarios does Office Online use one or the other?
2. If both are provided, how should a host respond?

**Comment by chrisbro-MSFT** [comment]
Yes, it is mutually exclusive.  They distinguish between whether the file name must be used exactly as provided (X-WOPI-RelativeTarget), or whether the host can change the filename (X-WOPI-SuggestedTarget).  For example, when we save a converted file (like from binary conversion) we just suggest a name and allow the host to change it.
