### ISSUE TITLE
RenameFile requests include invalid X-WOPI-Lock header values

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#130]
Per the documentation, RenameFile requests include a X-WOPI-Lock header value that should be checked against the current file lock. Otherwise the rename request should fail. However, currently Office Online does not send the correct X-WOPI-Lock header value, so the Rename feature does not work as expected.

We are working on a fix to send proper lock headers. In the meantime, hosts should ignore lock headers for RenameFile requests.

**Comment by parinmaru89** [comment]
@tylerbutler Does this happen for all apps? 
I have observed this issue with Word and Powerpoint.
Excel file renaming works perfect for me.

**Comment by JurRutten** [comment]
👍 
seeing this open issue sooner would have saved me a lot of time...

**Comment by tylerbutler** [comment]
This issue is now resolved in the *test environment*. Once we have validated the changes there, we'll roll it out to the production environment.

**Comment by tylerbutler** [comment]
There was a bug in the original fix, so this is still not addressed in either the test or production environments. A fix is in progress.

**Comment by tylerbutler** [comment]
This should now be resolved.
