### ISSUE TITLE
Clarify what is done with X-WOPI-InvalidFileNameError

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#14]
Is this message shown to the user?

**Comment by tylerbutler** [comment]
I think this is just logged by Office Online. @chrisbro-MSFT, can you confirm?

**Comment by chrisbro-MSFT** [comment]
If it's a rename and the filename the user chose is invalid, they should send an X-WOPI-InvalidFileNameError with a non-empty value. We'll log that value (to help with debugging) but it won't get displayed to the user.
