### ISSUE TITLE
SampleWopiHandler - removing locks

### ISSUE THREAD

**Issue by Ben-Gan** [Microsoft/Office-Online-Test-Tools-and-Documentation#147]
I think there is a bug in the SampleWopiHandler.

In most of the code, when referencing a lock the requestData.Id is used
For example
`TryGetLock(requestData.Id, out existingLock);`
`Locks[requestData.Id] = new LockInfo() { DateCreated = DateTime.UtcNow, Lock = newLock };`

But when removing a lock, the requestData.FullPath is used
For example:
`Locks.Remove(requestData.FullPath);`

This results in the file staying locked until the lock expires.
I discovered this by opening a Word document, editing then closing the browser.  When I opened the file again, it complains that the file is locked.

**Comment by tylerbutler** [comment]
Thanks for the report. We'll take a look. Feel free to send a pull request as well!
