### ISSUE TITLE
X-WOPI-ItemVersion required on PutFile, Lock, and Unlock responses

### ISSUE THREAD

**Issue by karvell** [Microsoft/Office-Online-Test-Tools-and-Documentation#176]
The documentation should say X-WOPI-ItemVersion is a required response on PutFile, Lock, and Unlock for partners doing the iOS/Mobile integration.

**Comment by tylerbutler** [comment]
I suggest putting this on the [requirements for iOS](https://wopi.readthedocs.org/projects/officewopi/en/latest/wopi_requirements.html) page.

**Comment by tylerbutler** [comment]
This was addressed in commit eb64f84.
