### ISSUE TITLE
More communication between host and office online (power point)

### ISSUE THREAD

**Issue by tuckdesign** [Microsoft/Office-Online-Test-Tools-and-Documentation#187]
I haven't found in docs, so asking here. Is there a way to get/set current slide in power point presentation using postMessage? Like 'StartPresentation', 'FullScreen', 'GoNext', 'GoPrevious', 'UI_CurrentSlide' and similar?
If this doesn't exist, is it planned to enable something like this? It would be really useful when using power point in embedded iframe on some web page.

**Comment by tylerbutler** [comment]
The available PostMessages are documented, and these don't exist at the moment. I suggest adding this suggestion to the UserVoice forum here: https://powerpoint.uservoice.com/forums/270149-powerpoint-online
