### ISSUE TITLE
Container Operations and Office Online

### ISSUE THREAD

**Issue by nickuraltsev** [Microsoft/Office-Online-Test-Tools-and-Documentation#196]
Hi! Are Container operations used by Office Online or they are only needed for Office for iOS?

**Comment by tylerbutler** [comment]
Office Online does not *currently* use the container operations, though it might in the future for hosts that support them. See here for the WOPI validator tests that must be passing for Office Online integration:

https://wopi.readthedocs.org/en/latest/build_test_ship/shipping.html#wopi-validation

**Comment by nickuraltsev** [comment]
Thank you for the quick response!
