### ISSUE TITLE
How to connect Office for iOS to WOPI service

### ISSUE THREAD

**Issue by nickuraltsev** [Microsoft/Office-Online-Test-Tools-and-Documentation#197]
Hi! How can we configure Office for iOS to work with our WOPI service? We've got Office Online working with our WOPI implementation, but it's not clear how to approach iOS integration.

**Comment by karvell** [comment]
The Office for iOS integration is documented here: https://wopi.readthedocs.org/projects/officewopi

With that said, please contact Microsoft if you are interested in doing the iOS integration, as it is not entirely self service. Sign up: http://dev.office.com/programs/officecloudstorage

**Comment by sparky742** [comment]
Can you explain "not entirely self service"?  Can't one do WOPI integration on a basic level without this?

**Comment by sparky742** [comment]
Can iOS connect to anything other than WOPI? (e.g. WebDAV)

**Comment by karvell** [comment]
In the link that I provided, http://dev.office.com/programs/officecloudstorage, there's a section on Integration via OS file picker. We do support the iOS document picker.

Onboarding currently requires work from Microsoft to onboard. There's a queue of partners that we're working through.  We're working on better documentation to make this more self service, but it's not there yet.

**Comment by sparky742** [comment]
Thanks for the rapid response.  I figured there might be something like that. We already use the picker, but it is a little too buried in Office for a good user workflow. Glad it is available as an alternative though!
