### ISSUE TITLE
Full Page View

### ISSUE THREAD

**Issue by jstenson** [Microsoft/Office-Online-Test-Tools-and-Documentation#221]
Hello,

I'm looking for a way to load a document where I can view the **entire page** or a way to set the zoom level with a parameter.

Currently I am using the action="embedview" and it cuts off the bottom portion of he page so I have to scroll to read it.  When I right click on the document I get an option to show "Full Page"  is it possible to pass parameters to set the default zoom level to "Full Page"?

**Comment by tylerbutler** [comment]
There's currently no programmatic way to set the zoom level on load. We don't have any near-term plans to add it.

**Comment by tylerbutler** [comment]
I'm closing this since I believe the question is answered. Please reopen if that's not the case.
