### ISSUE TITLE
All my tests except HostFrameIntegration on the validator failed with a NullReferenceException

### ISSUE THREAD

**Issue by adar237** [Microsoft/Office-Online-Test-Tools-and-Documentation#225]
Hello, 

I just finished implementation of a wopi host in Java. The CheckFileInfo and GetFile are accessible at the endpoints http://domain.com/wopi/files/(fileId)[/contents]. The second test group (BaseWopi) failed and I don't understand why. 

Here is how my restful is declared:

`@Stateless
@Path("wopi")
public class Wopi { 
......
}`

And here is the method for CheckFileInfo request : 

`  @GET

    @Path("/files/{idFile}")
    @Produces(MediaType.APPLICATION_JSON)
    public Response checkFileInfo(@QueryParam("access_token") String token, @PathParam("idFile") String idFile, @Context ContainerRequestContext containerRequest) {
        UriInfo info = containerRequest.getUriInfo();
        CheckFileInfo fileInfo = new CheckFileInfo();  // Class with CheckFileInfo properties
        TNewUser user = null;
        try {
            user = tokenService.validateToken(token, info.getPath()); // validate token; got null if not valid
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(Wopi.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(user == null){
            Response.ResponseBuilder responseBuilder = Response.status(Response.Status.UNAUTHORIZED);
            responseBuilder.entity("Unknown User");
            return responseBuilder.build();
        }`
   `     
        TFile f = tFileFacadeREST.find(idFile);   // Looking for file in DB

        if (f == null) {
            Response.ResponseBuilder responseBuilder = Response.status(Response.Status.NOT_FOUND);
            responseBuilder.entity("File not found");
            return responseBuilder.build();
        }
        fileInfo.setOwnerId(f.getOwner().getIdUser());
        fileInfo.setBaseFileName(f.getName() + (f.getFileExtension() != null ? "." + f.getFileExtension() : ""));
        fileInfo.setSize(f.getMaxSize());
        fileInfo.setVersion(f.getVersion());
        fileInfo.setUserId(f.getOwner().getIdUser());
        Response.ResponseBuilder responseBuilder = Response.ok((Object)fileInfo);
        responseBuilder.header("Content-Type","application/json");
        responseBuilder.header("X-WOPI-HostEndpoint","/wopi/files/"+idFile);
        responseBuilder.header("X-WOPI-MachineName",audit.getHostName(request));
        responseBuilder.header("X-WOPI-ServerVersion","1.0");
        return responseBuilder.build();
    }`

Here is the stack trace of the exception:

`CheckFileInfoFieldsNotToBeSetByHosts details
System.NullReferenceException: Object reference not set to an instance of an object.
at WopiValidator.Core.Requests.RequestBase.GetResponseData(HttpWebResponse response, Boolean isTextResponseExpected, TimeSpan elapsed)
at WopiValidator.Core.Requests.RequestBase.ExecuteRequest(RequestExecutionData executionData, String userAgent, Boolean hasToBeSuccessful)
at WopiValidator.Core.Requests.WopiRequest.Execute(String endpointAddress, String accessToken, Int64 accessTokenTtl, ITestCase testCase, Dictionary`2 savedState, IResourceManager resourceManager, String userAgent, RSACryptoServiceProvider proofKeyProviderNew, RSACryptoServiceProvider proofKeyProviderOld)
at WopiValidator.Core.TestCaseExecutor.ExecuteTestCase(ITestCase testCase)
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at WopiValidator.Core.TestCaseExecutor.Execute()
at Microsoft.Office.Web.WopiTestService.ExecuteTestMethod.ProcessRequest(HttpContext context)`

Can somebody help me to solve this issue please ?

**Comment by tylerbutler** [comment]
@adar237 Is your WOPI domain on the test environment [allow list](http://wopi.readthedocs.io/en/latest/build_test_ship/settings.html#wopi-domain-allow-list)? If not, then Office Online will refuse to make outgoing WOPI requests to your domain. This applies to the validator as well as all the apps.

**Comment by adar237** [comment]
@tylerbutler thank you for your answer. yes it is.

**Comment by tylerbutler** [comment]
@adar237 OK, please follow the [troubleshooting guide](http://wopi.readthedocs.io/en/latest/build_test_ship/troubleshooting.html) and provide a Fiddler trace of the validator page while it is executing the tests. That will give me enough info to diagnose the problem.

Also, if you're passing an [access_token_ttl](http://wopi.readthedocs.io/projects/wopirest/en/latest/concepts.html#term-access-token-ttl) value, try removing it. It possible you're using an invalid value there.

**Comment by adar237** [comment]
@tylerbutler thanks for your quick answer. I've followed the troubleshooting guide and when I activate the capture, I'm unable to access secure sites. As you can see in the attachment this is also the case of onenote.officeapps-df.live.com. Don't know how to do now. :(

![not_secure](https://cloud.githubusercontent.com/assets/12956991/16034303/ed70870c-3208-11e6-82f1-39df1c4ae2da.png)

**Comment by adar237** [comment]
@tylerbutler forget about my last comment I've been able to solve it (thanks to http://www.telerik.com/blogs/configuring-firefox-for-fiddler); now I can provide you the .saz file in the archive attached.
[trace.zip](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/files/313455/trace.zip)

**Comment by tylerbutler** [comment]
@adar237 Your WOPISrc points to a port other than 80 or 443: `http://www.niix2u.com:8282/wopi/files/...`

Office Online only makes outgoing network requests to ports 80 or 443 (and only 443 in production, since HTTPS is required in production).

**Comment by adar237** [comment]
@tylerbutler it's working now ; indeed I completely missed this points. Thanks once dude. :+1:
