### ISSUE TITLE
Error when opening a file for editing

### ISSUE THREAD

**Issue by adar237** [Microsoft/Office-Online-Test-Tools-and-Documentation#231]
Hello,
I implemented a Wopi host in java and it's working fine (thanks to @tylerbutler) when I try to view a file. But when opening a file for editing(/creation) I get the following error. 

"Sorry this document cannot be opened for editing"

This error appears when trying to edit a Microsoft Word (.docx) empty file. And the same when trying for Excel and Powerpoint too. I've implemented all the lock and update endpoints and tested them successfully with the [Wopi validator](https://wopi.readthedocs.io/en/latest/build_test_ship/validator.html) . So now I don't really know where is the problem, my app is using the Office Online test environment for WOPI discovery.

Need help please...

**Comment by tylerbutler** [comment]
If you can follow our [troubleshooting guide](http://wopi.readthedocs.io/en/latest/build_test_ship/troubleshooting.html) and provide us a Fiddler trace or at least a session ID, we can be more helpful.

**Comment by tylerbutler** [comment]
When you say it's an "empty file," do you mean that the file is zero bytes? Those are only supported in the [file creation flow](http://wopi.readthedocs.io/en/latest/scenarios/createnew.html), and you need to be sure you're using the `editnew` action in that case.

**Comment by adar237** [comment]
thanks @tylerbutler for your answer, I followed the file creation flow and used the `editnew` action for this file which is 0 bytes at its creation. 

Here is the session ID : `78ecf61b-3659-4ad2-80bb-1fc9de79fc3c`
I also attached the fiddler trace of the editnew action . 
Hope those will help. Thanks in advance.

[trace.zip](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/files/330427/trace.zip)

**Comment by tylerbutler** [comment]
@adar237 I'm seeing lots of errors in our logs that indicate that your responses to WOPI requests have a Content-Length HTTP header value that doesn't match the actual length of the response body. For example, the Content-Length header says the response is 317 bytes, but then there's no actual response body. This can cause problems; do you know what is causing your requests to mis-report their Content-Length.

**Comment by tylerbutler** [comment]
From what i see in our logs, all of your WOPI responses have incorrect Content-Length headed.

**Comment by adar237** [comment]
@tylerbutler I'm not setting this header in any WOPI request implementation. The only headers I'm setting are the [Standard response headers](https://wopi.readthedocs.io/projects/wopirest/en/latest/common_headers.html) and some others in case of lock conflict. :(

**Comment by adar237** [comment]
@tylerbutler here is a screenshot of my tests through the Wopi Validation platform. I've checked the content-length in all the validated requests and they are correct. I'm really confused about what is going wrong.
![screenshot](https://cloud.githubusercontent.com/assets/12956991/16411579/a60bbd6a-3d1f-11e6-8a7c-fd187bcb2f30.PNG)

**Comment by adar237** [comment]
@tylerbutler finally I have been able to detect the real issue. it was related to my putFile implementation. Thanks once for your help. :)

**Comment by tylerbutler** [comment]
Can you clarify if this is happening on all documents, or just when you try to create new ones? I don't see anything in our logs for the session ID you provided earlier other than the content-length thing.

**Comment by tylerbutler** [comment]
Good to hear you diagnosed this. I am closing this issue.

**Comment by sandeep2863** [comment]
hey @adar237  can you please tell me how you solve this issue, what are the header paramaters you are using for put request..
