### ISSUE TITLE
Add sample code and test cases for validating proof key implementations

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#25]
From @MarcinJuraszek:

There is a pair of inputs for each of possible cases:

1. Validate successfully using X-WOPI-Proof and current Key from Discovery
2. Validate successfully using X-WOPI-ProofOld and current Key from Discovery
3. Validate successfullyusing X-WOPI-Proof and old Key from Discovery
4. Validation fails

I generated those using custom certificate, all the keys information is included in the test code itself so it's not bound to any Certificate changes we make in our environments.

You can find the code on Gist: https://gist.github.com/MarcinJuraszek/54477a568c9a2ed851ef - just change `ProofKeysHelper.Validate()` method with your implementation of Proof Keys validation logic.

**Comment by MarcinJuraszek** [comment]
https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/pull/36/files
