### ISSUE TITLE
Dạy nấu món chả bò quấn mía miền Trung.

### ISSUE THREAD

**Issue by hocnauanngon** [Microsoft/Office-Online-Test-Tools-and-Documentation#251]
Xuất hiện nhiều trong các bữa tiệc gia đình Việt, món chả bò quấn mía tuy không phải là món ăn sang trọng, cầu kì, nhưng luôn được ưa thích bởi vị thơm ngon và cách chế biến độc đáo từ hoc nau an. 

Chả bò quấn mía không phải là món ăn xa lạ với những người đam mê ẩm thực miền Trung. Tuy không phổ biến nhiều như các món ăn thường thức khác trong bữa cơm gia đình, nhưng chỉ cần nhắc đến cái tên món ăn này thôi cũng khiến thực khách cảm thấy hấp dẫn. Vị thịt bò ngọt thanh hoà quyện cùng vị mía lùi dân dã mang đến sự tuyệt hảo của món ăn này.

Vào những dịp đặc biệt của gia đình, hãy trổ tài đầu bếp của bạn khi thực hiện món ăn ngon này với công thức nấu ăn ngon sau đây: [http://www.hoidaubepaau.com/day-nau-an/](http://www.hoidaubepaau.com/day-nau-an/)

**Nguyên liệu:**
•	Giò sống: 400g- 450g
•	Thịt bắp bò: 350g
•	Mỡ phần: 250g
•	Hành tím: 1 củ 
•	Tỏi: 2 củ
•	Tiêu sọ và tiêu xay: mỗi loại 1 muỗng cà phê
•	Nước mắm ngon
•	4 khúc mía lùi hoặc mía lau( mỗi khúc khoảng 50cm)

**Cách chế biến:** 
1. Sơ chế các nguyên liệu:
_ Rửa sạch thịt bắp bò rồi để cho ráo nước, cắt lát mỏng nhỏ vừa ăn
_ Mở phần đem cắt hạt lựu nhỏ 
_ Hành tím, tỏi khô bóc bỏ vỏ lụa, đem băm nhuyễn. 
_ Mía phải được rửa sạch, vạt bỏ phần mắt mía, để nguyên vỏ cho đẹp mắt, chẻ nhỏ thành những đoạn mía dài 10cm, dày khoảng 0,5-1cm.  

2.Cách làm:
+ Cho thịt bò vào máy xay thịt xay nhỏ, hoặc bạn cũng có thể bằm nhuyễn bằng dao. Sau đó, cho thịt vào chén riêng ướp với 1 muỗng cà phê nước mắm ngon, hành tỏi băm và tiêu sọ. 
+ Trộn thịt bò đã thấm ướp khoảng 15 phút với giò sống và mỡ phần. Lúc nào bạn trộn thêm 1 muỗng cà phê tiêu xay vào hỗn hợp này.
+ Thoa 1 ít dầu ăn vào lòng bàn tay, lấy một lượng thịt khoảng 2 muỗng canh dàn đều trên lòng bàn tay. Sau đó, đặt 2/3 que mía vào giữa rồi bọc thịt lại, tạo hình giống như 1 chiếc đùi gà nhỏ. 
+ Xếp các que chả bò quấn mía vào trong xửng hấp 5 phút rồi lấy ra cho nguội bớt. 
+ Tiếp đó, bắc lên bếp 1 chảo sâu lòng, cho dầu ăn vào đun sôi, rồi thả các miếng chả bò vào chiên sơ cho vàng mặt chả. Lấy ra đĩa thấm ráo dầu. 

3. Thưởng thức:
Món chả bò quấn mía thơm ngon, dai mềm đã vừa miệng sẵn. Tuy nhiên, bạn có thể dùng tương ớt để chấm thêm và ăn kèm với các loại rau sống, bún tươi cũng đều khiến món ăn này thêm tròn vị hơn. 

Chúc các bạn thực hiện thành công món này cho gia đình mình có thêm những bữa ăn chất lượng và ngon miệng nhé. 

Nguồn: [http://www.hoidaubepaau.com/](http://www.hoidaubepaau.com/)

**Comment by tylerbutler** [comment]
This doesn't appear to be related to Office Online or the WOPI protocol; closing.
