### ISSUE TITLE
Clarify GetFile and PutFile's response body

### ISSUE THREAD

**Issue by mnpenner** [Microsoft/Office-Online-Test-Tools-and-Documentation#255]
Maybe I've missed something, but I can't find where the response body for [GetFile](http://wopi.readthedocs.io/projects/wopirest/en/latest/files/GetFile.html) is documented. Is it the raw file contents, or what? If yes, are we expected to set the `Content-Length` header too?

CheckFileInfo has a clear [response](http://wopi.readthedocs.io/projects/wopirest/en/latest/files/CheckFileInfo.html#response) section, but most of the other file operations are missing a "Response" section. I'm implementing a WOPI host and I need to know what to return.

Side-note: Is Cobalt/.NET still needed to implement all the REST endpoints (namely editing)? Last time I attempted this in PHP I got stuck because I couldn't implement some of the operations without Cobalt (MS-FSHTTP[B] is nearly impossible to implement)

**Comment by tylerbutler** [comment]
Yes, the body of the response should just be the file content. I agree this could be clarified in the docs, so I'll re-title this issue and use it to track that change.

In general, few WOPI responses have bodies. Those that do _should_ explicitly note the body content in the docs. In fact, including a body when none is explicitly defined in the spec should be avoided, as [noted in the docs](https://wopi.readthedocs.io/en/latest/build_test_ship/testing.html#non-empty-response-body). In almost all cases where a body is defined in the spec, it will be JSON.

The answer to your other question is addressed [in the docs](https://wopi.readthedocs.io/en/latest/overview.html?highlight=cobalt#integration-process):

> If you are familiar with existing Office protocols, note that you don’t have to implement the [MS-FSSHTTP]: File Synchronization via SOAP over HTTP Protocol (Cobalt).

**Comment by tylerbutler** [comment]
And regarding `Content-Length` - in general you should include that header on all your responses, but that's more of an HTTP best practices thing, not a WOPI thing.

**Comment by mnpenner** [comment]
Awesome. New docs look great aside from the few things that are missing; I think this will be much easier to implement this time. Thanks for the speedy response!
