### ISSUE TITLE
How to limit the on-line user in co-authoring.

### ISSUE THREAD

**Issue by sicexpn** [Microsoft/Office-Online-Test-Tools-and-Documentation#280]
how to know when the user gets off the web co-authoring page? so that we can implement the limits of the online users

**Comment by tylerbutler** [comment]
I'm sorry but I don't understand the question. Can you clarify what you're trying to achieve and why?

If you need to know when editing or co-authoring is finished, see here: https://wopi.readthedocs.io/en/latest/faq/editing_finished.html

**Comment by tylerbutler** [comment]
I'm closing this since there's been no further response. Please re-open the issue if you have further issues or questions.
