### ISSUE TITLE
How to replace the text of the box

### ISSUE THREAD

**Issue by sicexpn** [Microsoft/Office-Online-Test-Tools-and-Documentation#281]
![image](https://cloud.githubusercontent.com/assets/5294920/20522434/3e7c819e-b0eb-11e6-97fd-a419f26ef76f.png)

**Comment by tylerbutler** [comment]
It's unclear what you're trying to achieve, but there is no way to change the content of particular error messages in Office Online.

I can see in your screenshot that you are using a WopiSrc on port 8080. Ports other than 80 and 443 (and only 443 in production) won't work. See #246.

**Comment by tylerbutler** [comment]
I haven't seen further responses here so I am assuming that you've gotten what you needed. I'm closing this issue, but please re-open it or add a new issue if you have further questions.
