### ISSUE TITLE
Issue selecting language (for spellchecking)

### ISSUE THREAD

**Issue by JurRutten** [Microsoft/Office-Online-Test-Tools-and-Documentation#286]
We have a file where the language is set to french (belgium) 
[template.docx](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/files/687028/template.docx)
When the file is edited online however, the language is always selected to something else.
Any ideas what might be wrong?

**Comment by tylerbutler** [comment]
@JurRutten Apologies for not responding to this earlier - it slipped through the cracks. [This section of the docs](https://wopi.readthedocs.io/en/latest/discovery.html#term-ui-llcc) explains how you can control the language used by Office Online.

I'm closing this issue, assuming my answer addresses your question. If not, please feel free to re-open.
