### ISSUE TITLE
Clarify Save flow in combination with WOPI Client not able to save

### ISSUE THREAD

**Issue by mkruitz** [Microsoft/Office-Online-Test-Tools-and-Documentation#287]
We implemented the "good weather" part of the WOPI protocol (Office Online Service) and are missing the error handling part.

Specifically:
When a [PutFile](https://wopirest.readthedocs.io/en/latest/files/PutFile.html#putfile) call to OOS is executed the WOPI client could be unable to save the document.
How can we:
- notify OOS that the WOPI client is unable to save
- give the user feedback that saving failed, eg "Sorry, your changes weren't saved. To continue editing this document, please copy your changes and refresh the page".

**Comment by tylerbutler** [comment]
@mkruitz I apologize for the delay in responding to this issue. I somehow missed it when you filed it earlier this year. I'm not sure what you're asking, though. Can you clarify?

If a WOPI client makes a PutFile request, then the WOPI server can respond with any HTTP code listed in the documentation. That is, the server could return a 401 or 404 to indicate that the user doesn't have permissions to edit the file. Or they could return a 409 to indicate that the file is locked and the PutFile request did not have the correct lock ID. Etc.

How the WOPI client behaves in response to these HTTP codes is dependent on the client.

**Comment by mkruitz** [comment]
@tylerbutler No problem. 

After retesting the failing scenario we cannot reproduce the results we had in Januari.
Our guess is that the dutch translations are updated / return a better message (eg. "Sorry, your changes weren't saved. To continue editing this document, please copy your changes and refresh the page" in dutch "Uw wijzigingen zijn niet opgeslagen. Kopieer uw wijzigingen en vernieuw de pagina als u dit documentbestand verder wilt bewerken.").
