### ISSUE TITLE
PowerPoint sends unexpected series of WOPI requests LOCK->PUT->UNLOCK in ~30 seconds after closing browser tab and unlocking document

### ISSUE THREAD

**Issue by flyinua** [Microsoft/Office-Online-Test-Tools-and-Documentation#303]

**Comment by flyinua** [comment]
Is it correct behavior?

In OfficeOnline logs i could see:

2/22/2017 07:21:56.41 w3wp.exe (0x16BC) 0x1C10Office
Online
PowerPoint editing ahjgm Medium AppManager::CheckForWebSessionTimeout - closing WebSession due to user
disconnecting or being Idle. WebSession - [WebSessionId:] bb6af9a6-36f7-4bf5-919b-18576eb4e7f9
02/22/2017 07:21:56.41 w3wp.exe (0x16BC) 0x1C10Office
Online
PowerPoint editing asp3e Medium WebSession::TryAddCloseSessionAction. Calling SaveAndClose before disposing.

after tab has been closed

**Comment by tylerbutler** [comment]
@flyinua Can you clarify if you're using the Office Online cloud service or Office Online Server? This sounds like an old bug in PPT that was fixed some time ago in the cloud service.

**Comment by flyinua** [comment]
@tylerbutler ,
Thank you for feedback

We use Office Online Server 2016 on premise. X-OfficeVersion: 16.0.7430.2228.
If its needed I can attach fiddler session and full logs.

**Comment by tylerbutler** [comment]
Thanks for clarifying. We can't offer support for Office Online Server issues here in this forum. The bug *sounds* like one that was fixed some time ago, but likely that fix has not yet made it into an OOS update. It should be in the next update. If you're seeing this behavior in the cloud service, please re-open this issue.

**Comment by flyinua** [comment]
Okay, thank you for help
