### ISSUE TITLE
Clarify that Office Online Server does not support cursor tracking in realtime coauthoring

### ISSUE THREAD

**Issue by kanno41** [Microsoft/Office-Online-Test-Tools-and-Documentation#304]
I've been looking for all sorts of documentation about this, but I cannot figure out how/why cursor tracking is not supported with Office Online Server (on-prem). 

Realtime editing works, just not the cursor tracking, and it's not documented anywhere as to why that occurs.

**Comment by MattGauthier** [comment]
Hi kanno41,

I work for Microsoft on Office Online. I'm working to connect you with the proper support process so we can track down this issue and help you out. 

In the meantime, can I ask have set up Office Online Server to restrict http: connections as described in [this article](https://technet.microsoft.com/en-us/library/mt346470(v=office.16).aspx)

If so, this is likely a known issue that we've recently fixed (and rolling out in September.) If not, then we'll need to engage with you to understand repro steps and investigate the issue you're having.

Thanks
Matt Gauthier (Microsoft)

**Comment by simakvladimir** [comment]
I have the same problem. Tracking cursor works perfect when OOS uses http connection but tracking is not working using https.
I install November 2017 release.

**Comment by tylerbutler** [comment]
We can't provide Office Online Server support here. If you want to receive assistance with that, you'll need to open a support ticket.
