### ISSUE TITLE
Ẩm thực chay, nét văn hóa của người Việt

### ISSUE THREAD

**Issue by phiphuonganh1995** [Microsoft/Office-Online-Test-Tools-and-Documentation#311]
Ăn chay là tập tục tín ngưỡng, văn hóa truyền thống lâu đời của các nước Á Đông, trong đó có Việt Nam. Ngày nay không nhất thiết người tu hành mà bất cứ ai thưỡng thức đồ ăn chay như một phương pháp chữa bệnh, và giữ gìn sức khỏe cũng như làm sạch tâm hồn.

Ăn chay, gốc từ chữ Hán là Trai, tức là giữ lòng được trong sạch. Xưa, có lệ trai giới, mỗi khi tổ chức lễ cầu nguyện với đất trời hay có việc tế tự trước 3 ngày ăn uống đồ chay (gọi là Trai), trước 7 ngày giữ gìn thành kính tâm niệm việc mình cầu nguyện (gọi là Giới).

Văn hóa ăn chay của người Việt thường xuất hiện từ lâu đời và đã được duy trì cho đến thời nay . Thời phong kiến trước khi tế trời ở Đàn Nam Giao, nhà vua sống biệt lập, cử ăn thịt cá ba ngày, không được 
thành kính tâm niệm việc mình cầu nguyện (gọi là Giới).

Văn hóa ăn chay của người Việt thường xuất hiện từ lâu đời và đã được duy trì cho đến thời nay . Thời phong kiến trước khi tế trời ở Đàn Nam Giao, nhà vua sống biệt lập, cử ăn thịt cá ba ngày, không được gần gũi với các cung phi, mỹ nữ. Ngày nay, nhiều người tuy không đến chùa Phật để quy y Tam Bảo cũng nguyện ăn chay vì lý do đó.Vả hoặc ông bà cha mẹ ăn chay, con cháu giữ lệ cũng ăn theo, để báo hiếu. Cũng có trường hợp ăn chay để ngừa bệnh cao huyết áp, ăn những món thực vật để giảm bớt đi lượng cholesterol trong máu.

Văn hóa ăn chay của người Việt ngày nay đã có bước tiến mới so với nhiều năm trước. Từ nhiều năm nay, ngay cả những đám cưới, đồ ăn chay, cỗ chay đã xuất hiện ngày một nhiều và sánh vai cũng với những món mặn khác. Các bữa cỗ chay, buffet chay cũng ngày càng phổ biến rộng rãi và thường xuyên hơn trước với số lượng món ăn nhiều hơn. Nguyên liệu sử dụng để nấu cỗ chay đang ngày càng trở nên nhiều chủng loại hơn và sự sáng tạo tìm tòi của đầu bếp để đồ ăn chay ngày càng phong phú hơn làm cho văn hóa ăn chay trở nên gần gũi, thân thiện hơn đối với người Việt nhất là đối với những người đến với ăn chay với một sự tò mò.

Người Việt tìm đến đồ ăn chay có rất nhiều mục đích. Tìm đến đồ ăn chay như một sự thưởng thức một nét ẩm thực đặc biệt, khác biệt hoàn toàn với những sơn hào hải vị đã nhàm chán và không tốt cho sức khỏe. Ăn chay để làm thanh tịnh tâm hồn sau những lo toan trăn trở, bộn bề của cuộc sống, có được chút thư giãn của tâm linh thật quý giá vô ngần. Để cuộc sống đơn giản mà năm tháng ít dành được sự bình tâm nhằm trở lại với cội nguồn của niềm an lạc. Ăn chay để tìm đến thú ẩm thực nhẹ nhàng mà nâng đỡ tâm hồn qua các bữa cơm chay thanh đạm, giúp cho chúng ta hướng đến bản, nguyện nguyên thủy. Ăn chay để bảo vệ, giữ gìn sức khỏe khi có ngày càng nhiều bệnh tật đeo bám con người. Tránh xa những món ăn độc hại, những loại thịt cá không đảm bảo tốt cho sức khoẻ của bản thân và của người thân. Ăn chay để bảo vệ môi trường, bảo vệ những loài sinh vật đang dần bị mai một vì con người…

Ăn chay đã trở thành một trong những nét văn hóa đẹp trong văn hóa ẩm thực của người Việt. Những bữa cơm chay đã xuất hiện ngày một nhiều trong những bữa cơm của gia đình Việt. Giới trẻ đã tiếp cận với nền văn hóa ăn chay nhiều hơn, khái niệm ăn chay không còn lạ lẫm với những người trẻ tuổi. Họ tìm đến những bữa cơm chay với một sự tò mò để rồi dần dần những bữa ăn chay đã đã trở thành một điểm đến thường xuyên của nhiều người.

Tìm đến những bữa ăn chay giờ đây đã không chỉ là thưởng thức những món ăn đặc biệt, những món ăn thanh đạm mà là còn là sự trải nghiệm, là để lắng nghe những câu chuyện về phật giáo, về nhân quả hành động của con người trong cuộc sống. Lắng nghe để cảm nhận, để chiêm nghiệm lại cuộc đời, chiêm nghiệm bản thân. Từ đó tìm cho mình một con đường đi đúng đắn hơn, làm tâm hồn của bạn trở nên thanh sạch hơn. 

Tìm hiểu thêm nhiều kiến thực ẩm thực hãy khác của Việt Nam tại đây bạn nhé : https://vuonglamchef.tumblr.com/

**Comment by tylerbutler** [comment]
Appears to be spam; closing.
