### ISSUE TITLE
[Word Online] Binary conversion fails if either HostViewUrl or HostEditUrl are omitted from PutRelativeFile response

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/Office-Online-Test-Tools-and-Documentation#313]
Both optional `HostViewUrl` and `HostEditUrl` properties must be included in the PutRelativeFile response, or the conversion will fail with a generic error. We are working on a fix for this issue.

In the meantime, the issue can be easily worked around by providing both `HostViewUrl` and `HostEditUrl` in the PutRelativeFile response.

**Comment by tylerbutler** [comment]
We are planning not to fix this behavior in Word Online. There are plenty of reasons why HostEditUrl and HostViewUrl should be included as a best practice anyway (see #192 and #324 for example), so we're planning to add a new validator test specifically for Office Online that requires these optional properties.

**Comment by tylerbutler** [comment]
Validator test was added in https://github.com/microsoft/wopi-validator-core/issues/30, so closing this.

**Comment by Ashraf111** [comment]
![hosturlerror](https://github.com/microsoft/Office-Online-Test-Tools-and-Documentation/assets/13987736/f9fdf54c-b963-4a92-9efb-d4941ad972a7)
i am facing this error would you please help me . I have modified this code for wopisrc value
with empty string in wopisrc it have same error

 private async Task<CheckFileInfoVm> GetFileUrlAsync(IWopiFile file, ClaimsPrincipal user, WopiActionEnum wopiAction = WopiActionEnum.View, WopiDocsTypeEnum wopiDocsType = WopiDocsTypeEnum.WopiDocs, WopiVersionableTypeEnum isVersionable = WopiVersionableTypeEnum.True)
 {
     string xxx = "https://wopistage.hoxro.com/wopi/files/"+file.Identifier;

     CheckFileInfoVm fileInfoVm = new CheckFileInfoVm();
     WopiClaimTypesVm claimTypesVm = await user.GetClaimInfoFromClaimIdentity();
     claimTypesVm.WopiSrc=xxx;
