### ISSUE TITLE
Bún thịt nướng chay cho ngày rằm

### ISSUE THREAD

**Issue by baongoc1998** [Microsoft/Office-Online-Test-Tools-and-Documentation#314]
Với món bún thịt nướng chay kiểu này mình thấy khá dễ làm, không cần làm tốn quá nhiều thời gian mà lại có 1 bữa chay thay đổi vị giác.

**Thành phần cần chuẩn bị trước**

10 miếng sườn non chay miếng lớn ( Vegan Soy Chop )

1 thìa canh hạt nêm nấm

2 thìa canh dầu hào chay

2 thìa canh xì dầu

1 thìa canh đường cát thốt nốt

1 thìa canh dầu mè

2 thìa canh dầu

Sả bằm, mè, ớt xay

**Các thao tác làm**

Bún thịt nướng chay cho ngày trăng tròn

Sườn chay ngâm cùng nước ấm, rửa xả thật rất rất nhiều cho đến khi sạch, vắt khô, xé mỏng sườn thành mảng miếng nhỏ.

Thêm vào hầu hết các hỗn hợp trên vào 1 cái thao to và quậy đều, thêm vào sườn chay vào và mang tay bóp cho sườn ngấm phụ gia khoảng chừng 10 ph.

Ghim sườn vào que tre cho lên vỉ nướng trên lửa than hoa đến khi chín vàng, hơi xém là được.

*** Chế biến nước mắm chay: Hòa tan nước dừa soda (hay coco) cùng đường trắng, xì dầu, muối và chanh. Quậy tan rồi cho ướt và tỏi vào (nếu không kiêng tỏi)
Dọn thịt nướng chay ăn kèm bún, rau xanh và dưa leo thái nhỏ.

Hy vọng các bạn hoàn thành công cùng với thử tài nấu ăn cùng với món bún thịt nướng chay trên

Các bạn có thể tham khảo thêm một số công thức làm món chay ngon khác tại đây nha : https://goo.gl/RjlLlc

**Comment by tylerbutler** [comment]
Seems to be spam; closing.
