### ISSUE TITLE
Muốn nấu súp Miso ngon hết sẩy như nhà hàng Nhật

### ISSUE THREAD

**Issue by baoanhtranblog** [Microsoft/Office-Online-Test-Tools-and-Documentation#318]
Súp Miso là một trong số các loại súp đặc trung tại đây của người Nhật. Hãy cùng với vào bếp thử sức món súp trứ danh này nhé!

**THÀNH PHẦN BẠN CẦN CHUẨN BỊ TRƯỚC**

2 miếng tảo biển to

6 tai nấm đông cô (nấm hương)

2,5l nước lọc

100 gram cá bào Nhật

1 miếng tàu hũ non, thái nhỏ

5 thìa canh sốt miso

200 gam rau cải

2 nhánh hành lá, cắt khoanh

**CÁC BƯỚC CHẾ BIẾN**

Thao tác 1

Cho tảo biển và nấm đông cô (nấm hương) ngâm sơ lược qua nước cho đến khi mềm.
Sau khi các bạn đã nở mềm, cho vào 2,5l nước lọc vào nồi. Ngâm khoảng chừng 1h. Rồi nấu cùng nhỏ lửa trong thời giản 35 phút.

Thao tác 2

Thêm vào cá bào vào nấu cùng. Kế đó vớt bỏ xác, nấm đông cô lấy xắt lát mỏng. Lấy nước chế đó, đổ rau và nấm vừa cắt vào nấu cho đến khi rau mềm.

Thao tác 3

Tiếp đó cho sốt Miso vào cùng tàu hũ non vào khuấy thật đều thêm vào 10 ph nữa là đã làm xong.

Tác phẩm: 

Súp Miso dễ làm đơn giản nhưng hương vị vẫn bảo đảm ngon mang đúng mùi vị Nhật Bản. Nước súp thanh ngọt ăn kèm nấm và tàu hũ non kèm rau cực kỳ thành công. Đây sẽ là món khai vị hoàn hảo hay là đồ ăn điểm tâm buổi sáng cho cả gia đình.

**Comment by tylerbutler** [comment]
Closing this as it appears to be spam.
