### ISSUE TITLE
WOPI - Editing excel documents gives you a "save as" options to save a copy on the server

### ISSUE THREAD

**Issue by viacob** [Microsoft/Office-Online-Test-Tools-and-Documentation#322]
Editing Word/PDF you can only download copies. 

For Excel documents, it gives you options to save in cloud, which doesn't make sense since we are only using the interface.

Is this expected behavior?

**Comment by tylerbutler** [comment]
@viacob I'm not sure I understand this issue. Are you asking why Excel has a "Save As" feature and how to disable it? If so, see the docs on [PutRelativeFile](https://wopi.readthedocs.io/projects/wopirest/en/latest/files/PutRelativeFile.html).

**Comment by viacob** [comment]
@tylerbutler it seems to be disabled but the actual "Save as" is still present in the client. Is there any way to disable the rendering of the saveas

**Comment by viacob** [comment]
@tylerbutler i followed both of these:

Set the UserCanNotWriteRelative property to true always.
Return a 501 Not Implemented to all PutRelativeFile requests.

Yet the save as still shows up in the web browser. And users can go ahead and click it and end up with an error message. How do I get the client to not show this rendering.

**Comment by tylerbutler** [comment]
@viacob I tried to reproduce this using my test WOPI host against the Office Online [test environment](https://wopi.readthedocs.io/en/latest/build_test_ship/environments.html#test-environment) and was unable to. When `UserCanNotWriteRelative` is `true`, the File -> Save As -> Save As button is properly trimmed. This is what I see:

![image](https://cloud.githubusercontent.com/assets/19589/26607077/874b6dfc-4549-11e7-94a3-11935bd18df6.png)

Can you follow [our troubleshooting steps](https://wopi.readthedocs.io/en/latest/build_test_ship/troubleshooting.html) and share a Fiddler trace, please?

**Comment by viacob** [comment]
spelling mistake on my part(UserCanNotWriteRelatve) ;/ SORRY!, closing for now.

Thanks again for all the help!

**Comment by tylerbutler** [comment]
@viacob I'm glad you were able to find the problem! Note that the WOPI validator has a test that would have caught the spelling mistake in the property name. It's always a good idea to check the validator results whenever something seems odd. 😄 Please let us know if you run into other issues.
