### ISSUE TITLE
CÁC CÁCH LÀM VỊT OM BIA CHANH NGON MỀM, BỔ DƯỠNG

### ISSUE THREAD

**Issue by monngonnoibat** [Microsoft/Office-Online-Test-Tools-and-Documentation#325]
Vịt om bia là đồ ăn cực kỳ lôi cuốn và rất là tốt cho thể trạng tốt. Hãy thực hiện các thao tác làm vịt om bia chanh ngon mềm & bổ dưỡng cùng với https://github.com/monngonnoibat

**Thành phần cần chuẩn bị để chế biến làm vịt om bia chanh**

+ Thịt vịt (470 gram)

+ Chanh (1 trái)

+ Một chút tiêu

+ Ngũ vị hương (sử dụng để ướp gia cầm)

+ Một ít muối

**Các cách làm vịt om bia chanh bổ dưỡng**

Quá trình 1

Chanh cắt đôi, vắt lấy nước, đổ 1/2 thìa cafe muối cùng 1/2 thìa coffe tiêu vào khuấy đều tay.

Quá trình 2

+ Thịt vịt làm sạch rồi đặt vào một cái bát sâu lòng Cho hỗn hợp nước chanh, một ít muối và tiêu bên trên bề mặt thịt vịt., thêm ngũ vị hương rồi xoa nhẹ sao cho phụ gia thấm đẫm khắp miếng thịt.

+ Phủ nilon bên trên bát thịt vịt đang tẩm ướp phụ gia rồi bỏ vào tủ lạnh khoảng chừng 6 tiếng. Nhớ, thi thoảng lấy ra lật lại miếng thịt.
Quá trình 3
+ Cho 1 thìa canh dầu vào chảo, khi dầu nóng, gắp miếng thịt vịt đã tẩm vào. Lưu ý đặt phần da vịt tiếp xúc cùng với dầu tầm chừng 5 ph cho ra hết mỡ và chín vàng như trong hình.

+ Kế đó, thả miếng vịt đã chiên vàng vào 1 chiếc nồi, trong đó đựng nước muối. Cho bia, một tí tiêu.

+ Đậy kín nắp nồi đun lửa to khoảng chừng 40 'p. Một số điểm chú ý trong quãng thời gian om lật miếng thịt vài lần để vịt chín đều.

+ Sau khi bạn đã thịt chín thì vớt ra, để nguội.
Quá trình 4

+ Cắt vịt thành miếng vừa miệng và bày trí cho đẹp mắt.

+ Lấy tầm chừng 150ml nước om vịt vừa xong, thêm dầu thực vật, một chút tiêu và muối, khi nước ấm rồi chan lên dĩa thịt vịt thay sốt.

Hoàn thành

Món thịt vịt thơm nứt muỗi với lớp da dai dai, đậm vị vị chanh và bia sẽ khiến cho những bữa cơm của cả gia đình bạn trở nên hào hứng hơn bao giờ tất cả. Hãy thuộc lòng các bước làm vịt om bia chanh và trổ tài vào bếp đầu bếp vào dịp cuối tuần (hay lễ tết) các bạn nha.

Hy vọng bạn hoàn thành công.

**Comment by tylerbutler** [comment]
Closing since this is spam.
