### ISSUE TITLE
15 phút có ngay bữa sáng thành công với bún thịt bò rau cần

### ISSUE THREAD

**Issue by monngoncuamom** [Microsoft/Office-Online-Test-Tools-and-Documentation#327]
Bún thịt bò rau cần sẽ không làm mất nhiều thời gian chuẩn bị trước, rất thích hợp cùng bữa sáng nhanh gọn đủ chất.

**PHẦN 1: THÀNH PHẦN CẦN CHUẨN BỊ ĐỂ CHẾ BIẾN**

- Xương bò: tầm chừng 2 kí

- Thịt bò: 500 gram

- Hành khô: 4 củ

- Cà chua: 3-4 trái

- Rau cần (hay rau cải, rau ăn cùng với)

- Phụ gia: nước mắm, hạt nêm, bột canh, một chút tiêu, ớt.

- Bún: 500 gram

- Hành hoa, rau răm, mùi.

**PHẦN 2: CÁCH CHẾ BIẾN BÚN THỊT BÒ RAU CẦN**

Quá trình 1: Xương bò làm sạch, rồi để khô nước. (Các bạn có thể nướng xương bò bằng lò nướng trong vòng 10 'p cùng với cách này sẽ làm các bạn khử mùi gây của xương bò). Sau khi bạn đã nướng xong, thì cho xương vào nồi chế ngập nước lọc, nước đun sôi chắt phần nước lọc bỏ đi rồi thêm vào nước đậy nồi áp suất và hầm tầm chừng Hai giờ. Tiếp đó chắt lấy nước lọc xương để riêng. (Cách này nên chuẩn bị trước từ tối để tiết kiệm thời gian)

Quy trình 2: Cà chua, rau cần, hành hoa, mùi xữ lý sạch. Cà chua bổ múi cau, rau cần phải cắt khúc. Hành hoa, mùi cắt nhỏ.

Quy trình 3: Thịt bò thái mỏng. (Nếu muốn bạn có thể tẩm thêm chút xíu phụ gia).

Quy trình 4: Phi thơm hành khô thái nhỏ cho cà chua vào xào, nêm nếm 1 muổng bột nêm cho cà chua mau mềm.

Quy trình 5: Cho phần cà chua vừa xào vào nồi nước lèo xương, nêm phụ gia cho vừa ăn.

Quá trình 6: Trong quá trình chờ đợi nồi nước chế xương sôi thì trần bún qua nước đun xếp vào tô. Nước lèo sôi hạ bớt lửa, cho rau cần, thịt bò vào trần, riêng rau cần nhúng chín rồi xếp vào bát bún cùng ít hành răm băm nhỏ, một vài lát ớt hiểm rồi từ từ chan nước lèo ngập bún.

Vậy là các bạn đã có bát bún bò cực ngon dành cho bữa sáng rồi nha.

Hy vọng các bạn ăn ngon miệng cùng với các cách làm bún thịt bò rau cần nhanh gọn dành cho bữa sáng!

**Comment by tylerbutler** [comment]
Spam; closing.
