### ISSUE TITLE
Business user flow: PowerPoint Online locks file during session start

### ISSUE THREAD

**Issue by nbashkankov** [Microsoft/Office-Online-Test-Tools-and-Documentation#331]
Hello, @tylerbutler 

I found closed issue - https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/issues/181 (Business user flow: Excel Online locks file during session start)

But, same happens with PowerPoint Online. File locked before user sign-in with MSFT account.
Even more, after successfully signing in, PowerPoint Online shows like two users (in top-right corner) with same name has editing session (like *user co-editing with himself*).

As result, after exiting from PowerPoint Online (via File -> Exit) lock for file not removing for long period of time (about several minutes instead of several seconds before), because of this editing session duplication i guess.

Could you clarify this case, and provide some info when it will be fixed?

**Comment by tylerbutler** [comment]
@nbashkankov Can you provide some example session IDs where you saw this behavior in the test environment? That will help us investigate if this is a recent regression.

**Comment by nbashkankov** [comment]
Hello, @tylerbutler 

Sorry for long response.

I see this behavior in production environment. 

Here ids before login:
'x-wopi-machinename': 'NLSWACWEB104',
'x-wopi-clientversion': '16.0.8330.1000',
'x-wopi-correlationid': '9afdb223-fb43-45df-82c3-102bbfa2e86a',
'x-wopi-appendpoint': 'NL1S',

'x-wopi-machinename': 'NLSWACWEB104',
'x-wopi-clientversion': '16.0.8330.1000',
'x-wopi-correlationid': '8bf585e8-3ac5-44bf-9b56-db5ffa45d250',
'x-wopi-appendpoint': 'NL1S',

and even lock requests with same correlationid (lock before login in)
'x-wopi-override': 'LOCK',
'x-wopi-machinename': 'NLSWACWEB132',
'x-wopi-clientversion': '16.0.8330.1000',
'x-wopi-correlationid': '9afdb223-fb43-45df-82c3-102bbfa2e86a',
'x-wopi-appendpoint': 'NL1S',

Next I log in with MSFT account and see several requests with those ids:
'x-wopi-correlationid': 'be980b72-3058-4743-98a7-cab02370314e',
'x-wopi-correlationid': 'c961285a-656f-4834-9550-4dd45a912f3b',
'x-wopi-correlationid': '921fdca6-a264-4300-8efb-2765f48a1a86',
'x-wopi-correlationid': 'fcfc5dd3-54d1-4f70-8d7d-fac590d67312',
'x-wopi-correlationid': '80fb5fd9-64de-43e7-beb4-9c7a4f356196',
'x-wopi-correlationid': '48a91524-7a99-4b00-b299-ef16e7985501',
'x-wopi-correlationid': 'a2da116a-7e8c-4f68-bd9e-f5566be26561',

**Comment by tylerbutler** [comment]
@nbashkankov To confirm, you do *not* see this in the test environment?

**Comment by nbashkankov** [comment]
@tylerbutler i cannot check this in test environment, because both of test accounts (provided from Cloud Storage Partner Program Yammer group), unable to use Office Online editing.
I tried with officeonlinetest_licensed1@officeonlinetest1.ccsctp.net and officeonlinetest_licensed2@officeonlinetest1.ccsctp.net - for both of them i see, after login on https://login.windows-ppe.net :
"You don't have an Office Online license
Your Office 365 account does not have an Office Online license assigned to it"

Any thoughts how to check this in Test environment (aka Dogfood)? 
Could you fix those accounts or provide new ones?

**Comment by tylerbutler** [comment]
This is tracked by internal bug 1767278.

**Comment by tylerbutler** [comment]
This bug was resolved several months ago but this issue wasn't closed as it should have been.
