### ISSUE TITLE
The Cloud Partner Storage Link is broken

### ISSUE THREAD

**Issue by serbentraut** [Microsoft/Office-Online-Test-Tools-and-Documentation#346]
If you try to fill out the form to register as a cloud partner here: https://dev.office.com/programs/officecloudstorage# you receive an error. Is there another way to register, or is this just a bug that needs to be fixed?

**Comment by mikeholtkamp** [comment]
I have the same issuue could you indicate if this will be fixed in the near futher

**Comment by tylerbutler** [comment]
@serbentraut @mikeholtkamp Apologies for the delay; we're aware of the issue and are working on a fix.

**Comment by tylerbutler** [comment]
@serbentraut @mikeholtkamp This should now be resolved. Please feel free to re-open this issue if you still have problems.
