### ISSUE TITLE
Need a complete solution for test

### ISSUE THREAD

**Issue by mohebbo** [Microsoft/Office-Online-Test-Tools-and-Documentation#351]
Hi Tyler ,
This is Mohebbo. i am trying to implement your test solution. I am facing issue on access_token and access_token_ttl. do you have a complete solution for this. i have already install office online server 2016 and try to implement your solution.

Thanks
Mohebbo

**Comment by tylerbutler** [comment]
Hi @mohebbo please move these questions and discussion to the CSPP Yammer group, since that's a better place for discussion about specific issues (as opposed to issues with the documentation).
