### ISSUE TITLE
/hosting/WopiTestFrame.aspx  Validation Application doesn`t work

### ISSUE THREAD

**Issue by puch868** [Microsoft/Office-Online-Test-Tools-and-Documentation#352]
Office Online Server 2016 local closed network installation.
View and Editing documents functions work successful.
Convert binary file doesn't work.
Co-authoring work only for one user (one user in two windows) only Excel.
I trying to find mistakes in my implementation in vain.
Validation Application doesn't work. I have two actions in hosting/discovery.
All of them let to server error Location:/error.html?aspxerrorpath=/hosting/WopiTestFrame.aspx
without any CorrelationId.

**Comment by tylerbutler** [comment]
Hi @puch868 - the WOPI validator is not expected to work in Office Online Server. It is a cloud service-only thing. The validator was erroneously advertised in WOPI discovery in a previous OOS release but that is fixed in the version released earlier this month.

**Comment by puch868** [comment]
Do you have any idea ? Why binary documents conversion  doesn't work.
I send http request to http://oos.local/we/WordConvertAndEdit.aspx?WOPISrc=http://my.domain/wopi/files/6233/?access_token=xxxxxxxxxxxxxxxxx 
I check the URL http://my.domain/wopi/files/6233/ it returns correct CheckFileInfo result:

_{"BaseFileName":"test.doc","OwnerId":"ownerid","UserId":"userid","UserFriendlyName":"userName","Version":"2","Size":3992,"UserCanWrite":"true","SupportsUpdate":true}_


And I check _http://my.domain/wopi/files/6233/contents_ it returns correct file content.
But when I try to invoke conversion  App (_http://oos.local/we/WordConvertAndEdit.aspx?WOPISrc=http://my.domain/wopi/files/6233/?access_token=xxxxxxxxxxxxxxxxx_ )
I have a blank page. In html code of this page I  can see content of conversion  dialogs 

`<body class="word " dir="ltr" onload="WopiConverter.SetupAndRun()">`

In headers I see X-CorrelationId, and go to office online serve to read logs. 
Office Online Server doesn't try to send PutRelativeFile request and doesn't try to take file from wopi host.

But editing of docx documents is successful. That uses the same WOPISrc path;

`Line 23526: 11/24/2017 10:56:17.17 	w3wp.exe (0x132C)                       	0x03D4	Office Online                 	Office Online common          	ajba4	Medium  	WAC Server HttpModule: Beginning request at target [/we/WordConvertAndEdit.aspx?&ui=ru-Ru&showpagestats=0&WOPISrc=http%3A%2F%2Fmy.domain%2Fwopi%2Ffiles%2F6239%2F%3Flang%3Dru%26access_token%3DREDACTED_32] in session [62131c05-fb8b-4c75-91d7-3269efee8a73] server build [16.0.7766.8550] client build [0.0.0.0]	62131c05-fb8b-4c75-91d7-3269efee8a73
	Line 23526: 11/24/2017 10:56:17.17 	w3wp.exe (0x132C)                       	0x03D4	Office Online                 	Office Online common          	ajba4	Medium  	WAC Server HttpModule: Beginning request at target [/we/WordConvertAndEdit.aspx?&ui=ru-Ru&showpagestats=0&WOPISrc=http%3A%2F%2Fmy.domain%2Fwopi%2Ffiles%2F6239%2F%3Flang%3Dru%26access_token%3DREDACTED_32] in session [62131c05-fb8b-4c75-91d7-3269efee8a73] server build [16.0.7766.8550] client build [0.0.0.0]	62131c05-fb8b-4c75-91d7-3269efee8a73
	Line 23527: 11/24/2017 10:56:17.17 	w3wp.exe (0x132C)                       	0x03D4	ULS Logging                   	Logging Correlation Data      	xmnv	Medium  	UserSessionId=62131c05-fb8b-4c75-91d7-3269efee8a73	62131c05-fb8b-4c75-91d7-3269efee8a73
	Line 23527: 11/24/2017 10:56:17.17 	w3wp.exe (0x132C)                       	0x03D4	ULS Logging                   	Logging Correlation Data      	xmnv	Medium  	UserSessionId=62131c05-fb8b-4c75-91d7-3269efee8a73	62131c05-fb8b-4c75-91d7-3269efee8a73
	Line 23528: 11/24/2017 10:56:17.17 	w3wp.exe (0x132C)                       	0x03D4	Services Infrastructure       	Services Infrastructure Logging	a22ei	Medium  	CheckBaseDocumentInternal: {"UserLogString":"","RequiresVersion":false,"fUserCacheLookup":true,"BaseDocumentCache":true,"IsChecked":true,"IsMiniChecked":false}	62131c05-fb8b-4c75-91d7-3269efee8a73
	Line 23529: 11/24/2017 10:56:17.17 	w3wp.exe (0x132C)                       	0x03D4	Office Online                 	Office Online common          	af46w	Medium  	WACServer HttpModule: Completed request with status code [200]	62131c05-fb8b-4c75-91d7-3269efee8a73
`

**Comment by tylerbutler** [comment]
Closing since we can't provide support for Office Online Server through this repo.
