### ISSUE TITLE
Why office online server sends two LOCK request ?

### ISSUE THREAD

**Issue by puch868** [Microsoft/Office-Online-Test-Tools-and-Documentation#353]
When I debug my WOPI host, I see that office online server send two request LOCK for one file.
first request with short X-WOPI-Lock string:
`[X-WOPI-Lock] =>{"S":"9d578795-b390-456b-affe-cc3c68078ea9","F":4}`
second request with longer X-WOPI-Lock string:
`[X-WOPI-Lock] => {"S":"9d578795-b390-456b-affe-cc3c68078ea9","F":6,"E":2,"M":"690fa7865d594d02a3d458a39b5e79db","P":"088008EE-9FA3-48CA-A8C0-2E3A0E455F30"}`

What string I need  save and comparasing.

**Comment by RobRol** [comment]
Yes, Word Online does send multiple lock operations during load.  From a WOPI implementation perspective, you can treat the Office Online internals as a black box.  What is important is that you have a standards compliant implementation of the [Lock API call](http://wopi.readthedocs.io/projects/wopirest/en/latest/files/Lock.html).  That said, I was pretty sure that one of the calls was an [UnlockAndRelock](https://wopirest.readthedocs.io/en/latest/files/UnlockAndRelock.html) call,  Have you checked?

Said differently, you should respect both calls.  In your example, assuming the file isn’t already locked, and assuming both calls are regular Lock calls... then the first call should succeed (status code 200).  The second call should fail with status code 409, and should return the lock taken by the first call as the response’s X-WOPI-Lock header.

Finally, I should call out that the GitHub repo is not the source to request help for Office Online Server (OOS).  We cannot provide support for that product through this channel.

**Comment by tylerbutler** [comment]
Closing this since I think Rob's answer addresses this.
