### ISSUE TITLE
No request made after time-out and refresh message in OOS

### ISSUE THREAD

**Issue by kamzolcsg** [Microsoft/Office-Online-Test-Tools-and-Documentation#358]
When using Word Online and using our custom Wopi-host, after a while a time-out while editing a document. Followed by a message (translated from Dutch: "Your session has expired. Refresh the page to continue.") after this text there is a button with the text "Refresh" (see attachment). Pushing the button does not trigger any event, at least no event is coming into our WopiHost.
The questions are:
- What should this button do?
- How can we create an event handler for this button (if possible).
- Is there a way to disable this button.

Our users now have the following scenario:
- They make some edits, OOS saves them (requests are processed by our WopiHost)
- They make more edits and OOS displays that the document is saved (no requests are received by our WopiHost).
- The above message appears and they click the button, but nothing happens.

The edits that are not saved (OOS says they are, but they are not received in our WopiHost) are the problem.

Thank you for your help.
![oos](https://user-images.githubusercontent.com/38003984/38194951-66126d08-366a-11e8-92f2-727c1262b0cc.jpg)

**Comment by tylerbutler** [comment]
We can't provide Office Online Server support here. That said, I will forward this report to the Office Online Server folks.
