### ISSUE TITLE
Office Online Server corrupts documents (pctWidth and pctHeight elements)

### ISSUE THREAD

**Issue by geraetscsg** [Microsoft/Office-Online-Test-Tools-and-Documentation#360]
After upgrading our development office online server from version 16.0.7601.6800 to the latest one (version 16.0.8471.8525) we observed certain Word documents got corrupted after they were edited. Even a local Word 365 can't open such a document.

In production, we still have the older version of office online server running (luckily), which does not corrupt the documents when editing, so I was able to compare the results.
Finally we were able to pinpoint what gets corrupted in the documents:
All corrupted documents have in common that they contain some sort of drawing element (for example a very simple rectangle with a color). In the original document this drawing element has its PercentageWidth and PercentageHeight specified as `<wp14:pctWidth>0</wp14:pctWidth>` and `<wp14:pctHeight>0</wp14:pctHeight>` respectively. After editing, the document (now corrupt) contains `<wp14:pctWidth />` and `<wp14:pctHeight />`. So empty values.

Does anyone have a solution for this problem? Can this be fixed in some way? We can't prevent users from adding such problematic documents and fixing corrupted documents is a hopeless task.

Attached is a simple document that, when edited on our office online server version 16.0.8471.8525, gets corrupt.
[corruptsOnEdit.docx](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/files/1920114/corruptsOnEdit.docx)

**Comment by tylerbutler** [comment]
We can't provide Office Online Server support here. That said, I will forward this report to the Office Online Server folks.

**Comment by tylerbutler** [comment]
This issue is indeed known and a patch with a fix is in process.
