### ISSUE TITLE
The Cloud Partner Storage Link is broken again

### ISSUE THREAD

**Issue by glasscubes** [Microsoft/Office-Online-Test-Tools-and-Documentation#361]
It seems to have already been an issue in Sept https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/issues/346

Basically you cannot register. I've tried all browsers and different types of information. You just get the error "Error: Something went wrong while submitting the form. "

**Comment by chrisbro-MSFT** [comment]
Thanks!  The two people whom I know can fix this are both out of office this week.  I'll have them take a look at it on Monday.  Apologies for our bug.

**Comment by jrodritena** [comment]
Is there any update on this issue? We have tried to register but we still see the same issue.

Thanks,

**Comment by glasscubes** [comment]
Hi,

could we please have an update? Many thanks

**Comment by glasscubes** [comment]
Seems to be working again. 
Thanks
