### ISSUE TITLE
Integration with SharePoint Online

### ISSUE THREAD

**Issue by fredrik-epidot** [Microsoft/Office-Online-Test-Tools-and-Documentation#369]
Is it possible to integrate with SharePoint Online? We want to give our users in our own application the possibility to edit and view documents that are stored inside SharePoint Online sites inside our own application.

I can't find any information about this in the documentation.

**Comment by tylerbutler** [comment]
@fredrik-epidot The documentation here is for direct Office Online and Office Mobile integration for storage hosts as part of Microsoft's Cloud Storage Partner Program. Unfortunately we can't address questions outside the scope of that program.
