### ISSUE TITLE
Rendering Excel files In Browser Through Office Online via WOPI Protocol

### ISSUE THREAD

**Issue by shahamit** [Microsoft/Office-Online-Test-Tools-and-Documentation#370]
I am trying to understand the overall integration flow to integrate a enterprise web application with Office Online to render Excel files in browser. I understood the overflow by going through the documentation but I have a few questions

1. Is the excel file rendering responsive on mobile (both android & iOS)? I understand the file rendering is responsive when viewed in the excel mobile app but the question is mainly about rendering it inside our app which is a hybrid (cordova based - web view) app.
2. Can we install Office Online server on-premise when using it for rendering excel files in production mode?
3. Do we need to implement authentication given that the application from which the user clicks on the file has authentication mechanism already in place? In this context a related question is do we need to generate access tokens?
4. If we go with the Office online server deployment in the microsoft cloud, would it be a dedicated server deployed for our needs? Would it be scalable based on the server load?

Thanks.

P.S - I couldn't find a better channel to get my questions clarified hence posting as an issue.

**Comment by tylerbutler** [comment]
Please raise these questions in the CSPP Yammer group.
