### ISSUE TITLE
WOPI - Excel documents do not switch to edit mode when clicking on "Edit in Browser" button.

### ISSUE THREAD

**Issue by baronntambwe** [Microsoft/Office-Online-Test-Tools-and-Documentation#371]
I have a WOPI service which returns in its CheckFileInfo all required data including:  
"UserCanWrite": true, 
"EditModePostMessage": true, 
"UserCanNotWriteRelative": true, 
 "HostEditUrl": "https://domain.com/Home/Detail/fileId?action=edit",
  "HostViewUrl": "https://domain.com/Home/Detail/fileId?action=view".

However, when WOPI returns the Excel in View mode, clicking on "Edit in Browser" button does not swhich the document into Edit Mode.

What could be the cause? Are we missing anything?

**Comment by tylerbutler** [comment]
You’ve told the app to send a post message when the button is clicked (EditModePostMessage=true), so it’s sending that message when the button is clicked, and nothing else. If you’re not handling the message, then the button will appear to do nothing.

Either don’t use the post message by removing that property in check or add your own post message handling code and redirect to edit yourself. That’s what the post message is intended to enable.
