### ISSUE TITLE
WOPI -  Opening Excel document in view mode does not trigger business flow validation

### ISSUE THREAD

**Issue by boagorudolph** [Microsoft/Office-Online-Test-Tools-and-Documentation#373]
I have a WOPI service which returns in its CheckfileInfo all required properties for indicating that the user is a business user. 

The BUSINESS_USER value is also properly set to true in both the edit and view actions.
For edit action, the edit capabilities are properly validated by redirecting user to a signing page to validate their commercial Office 365 subscription.

The argument that my colleagues have is that the same should happen for view action.
However [WOPI documentation](https://wopi.readthedocs.io/en/latest/scenarios/business.html#business-editing) does not indicate this.

Is view action suppose to trigger business user validation flow?

**Comment by tylerbutler** [comment]
The license check currently only applies to document editing. However, you must still identify users as business users regardless of the mode you use; the apps will determine whether a license check is needed.
