### ISSUE TITLE
files greater than 100KB not saving

### ISSUE THREAD

**Issue by phanikmr** [Microsoft/Office-Online-Test-Tools-and-Documentation#375]
When file reaching a size greater than 100KB while editing and every other file which is greater than 100 KB files are showing initially autosaved and later showing a message like this and actually files are not saving
![issue](https://user-images.githubusercontent.com/18280712/44918151-e6c17c00-ad57-11e8-8c03-36eea89f9c26.png)

**Comment by RobRol** [comment]
Howdy @phanikmr,

Can you please clarify if you're using the Office Online cloud service or Office Online Server?

Best regards,
Rob Rolnick

**Comment by phanikmr** [comment]
I'm using OOS 2016 and implemented wopi host in node.js

**Comment by RobRol** [comment]
We can't provide Office Online Server support here.  If you want to receive assistance with that, you'll likely need to open a support ticket.  I'm not sure of the exact location to do that, [but you can probably start here](https://support.microsoft.com/en-us/assistedsupportproducts).
