### ISSUE TITLE
how can i remove the header of  page

### ISSUE THREAD

**Issue by Meiling111** [Microsoft/Office-Online-Test-Tools-and-Documentation#383]
hello every body ,i am using office online and i want to remove the title when i am viewing or edting like this that the excel icon，word icon and ppt icon but i cant find the way,i need some help ,if you konw please answer the questione,Thanks in advance!

**Comment by tylerbutler** [comment]
Hello, please use the CSPP Yammer group for technical questions about the Office Online applications.
