### ISSUE TITLE
Office Online With language pack

### ISSUE THREAD

**Issue by mohdimran043** [Microsoft/Office-Online-Test-Tools-and-Documentation#394]
I have configured office online and viewing documents using custom WOPI in my MVC application. Everything seems to be except the numbers shown in the Word document are in English not in locale that i am passing.

I have done the following but still its not showing me numbers in local language. 
a. Changed the Language and regional setting to **Arabic**. 
b. Changed the Keyboard setting to **Arabic**.

Kindly let me know if i have to do any additional configuration to office online to get the desired result in my program

**Comment by tylerbutler** [comment]
@mohdimran043 Please use the Cloud Storage Partner Program group on Yammer for support.
