### ISSUE TITLE
Word online auto-save problem

### ISSUE THREAD

**Issue by ztwz** [microsoft/Office-Online-Test-Tools-and-Documentation#395]
When office online is automatically saved, the contents of the cursor are pasted repeatedly and saved.

For example:

There's a paragraph in word online: Hello word.

Re-refresh after auto-saving, may appear as follows: Hello word...

He will copy and save the contents of the last cursor location many times. (Sometimes it doesn't happen)

How can I solve this problem? English is not good, use translation software to translate,

**Comment by tylerbutler** [comment]
Sorry, but we can't offer support through this repository. If you are integrating with Office Online as part of the [Cloud Storage Partner Program](https://developer.microsoft.com/en-us/office/cloud-storage-partner-program), then you will receive an invitation to a Yammer group for support as part of onboarding.
