### ISSUE TITLE
Visio editing is not supported in the CSPP

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/Office-Online-Test-Tools-and-Documentation#398]

**Comment by lfcgomes** [comment]
@tylerbutler @borisf-msft is this fixed already or it's still not possible to edit a visio file in the CSPP?

**Comment by RobRol** [comment]
@lfcgomes - Per the [Cloud Storage Partner Program documentation](https://developer.microsoft.com/en-us/office/cloud-storage-partner-program#:~:text=The%20Microsoft%20Cloud%20Storage%20Partner%20Program%20%28CSPP%29%20enables,storage%20solution%2C%20with%20minimal%20development%20time%20and%20effort.) only Word, Excel, and PowerPoint documents are included as part of the program.  My read of that documentation suggests that Visio is not part of the program.

**Comment by lfcgomes** [comment]
@RobRol oh, I see. Thank you for the explanation!
