### ISSUE TITLE
I can't read xlsx file

### ISSUE THREAD

**Issue by wuqinqiang** [Microsoft/Office-Online-Test-Tools-and-Documentation#400]
I set up WOPI client and providing CheckFileInfo api，that can read Doc and PPTX ,but can‘t  read Xlsx, it's show I'm sorry I can't open your workbook.why?
`
 public function actionFileAddress()
    {
        $path = 'test/test.pptx';
       // $path = 'test/test.docx';
          $path = 'test/test.xlsx';
        $url = '';
        $file = fopen($path, 'rb');
        $finfo = finfo_open(FILEINFO_MIME);
        $type = finfo_file($finfo, $path);
        fclose($file);
        switch ($type) {
            case self::PPTX:
                $url = 'http://xxxxx/p/PowerPointFrame.aspx?&WOPISrc=';
                break;
            case self::DOCX:
                $url ='http://xxxxx/wv/wordviewerframe.aspx?&WOPISrc=';
                break;
            case self::XLSX:
                $url='http://xxxxxx/x/_layouts/xlviewerinternal.aspx?&WOPISrc=';
                break;
            default;
        }
		$file_url='http://xxxxx/wopihost/files/path?path=';
		$file_url .=urlencode($path);
		$wopiClent=$url.urlencode($file_url);
         return $this->redirect($wopiClent);
    }

    //返回文件信息，暂时不是写的接口
    public function actionGetfileinfo($path)
    {
        if (file_exists($path)) {
            $handle = fopen($path, "r");
            $size = filesize($path);
            $contents = fread($handle, $size);  
            $SHA256 = base64_encode(hash('sha256', $contents, true)); 
            $json = array(
                'BaseFileName' => 'haaha',
                'OwnerId' => 'admin',
                'Size' => $size,
                'SHA256' => $SHA256,
                'Version' => '222888822',
		'UserCanWrite'=>true
            );
            return json_encode($json);
        } else {
            echo json_encode(array());
        }
    }
`
and other question is  when  I want to update the pptx  , then set 'UserCanWrite'=>true,but it's show This demo file cannot be opened because it has been blocked by administrative policy.

Finally, I may not express well, my code is not well written, I hope you can help me solve the confusion, thank you.

**Comment by tylerbutler** [comment]
Hello, please use the CSPP Yammer group for technical questions about the Office Online applications.

**Comment by wuqinqiang** [comment]
> 您好，请使用CSPP Yammer小组获取有关Office Online应用程序的技术问题。
I don‘t understand what you mean,Can you give the address directly?My God, this problem has been bothering me for many days. Thank you

**Comment by tylerbutler** [comment]
@wuqinqiang We can't offer support through this repository. If you are integrating with Office Online as part of the [Cloud Storage Partner Program](https://developer.microsoft.com/en-us/office/cloud-storage-partner-program), then you will receive an invitation to the Yammer group as part of onboarding.
