### ISSUE TITLE
How to capture the Refresh event

### ISSUE THREAD

**Issue by ZeroneBit** [microsoft/Office-Online-Test-Tools-and-Documentation#403]
In my project, I've implement a WOPI server. Sometimes, oos prompt the message 'Sorry, your changes weren't saved. To continue editing this document, please copy your changes and refresh the page', But if I click the Refresh button, there is nothing happend. 
My question is how to capture this refresh event in my WOPI server?
![690_Word%20Online%20cannot%20refresh](https://user-images.githubusercontent.com/3735611/57421440-689a6b00-723e-11e9-8d49-563dd6a2482c.gif)

**Comment by tylerbutler** [comment]
Sorry, but we can't offer support through this repository. If you are integrating with Office Online as part of the [Cloud Storage Partner Program](https://developer.microsoft.com/en-us/office/cloud-storage-partner-program), then you will receive an invitation to a Yammer group for support as part of onboarding.
