### ISSUE TITLE
Access to Storage Partner Program

### ISSUE THREAD

**Issue by stap123** [microsoft/Office-Online-Test-Tools-and-Documentation#415]
I know this isn't the correct place to try and get help but I couldn't find another way to contact anyone on the team directly.

@tylerbutler 

We have recently changed our company Office 365 subscription from GoDaddy to be direct with Microsoft. During this process we have lost access to the Yammer group. Can you help with regaining access and transferring the details to the new 365 tenant? 

(I have submitted another request on the website but the information will be the same as the existing one so I'm concerned it won't be processed as it will look like we are already there)

Edit: 15/04/2020 19:04
Janine Boher (Launch Consulting) has added us but the links I received are broken and not working.

**Comment by tylerbutler** [comment]
@stap123 Please continue working with Janine.

**Comment by stap123** [comment]
Thanks @tylerbutler , we got added with my personal email address in the end because the company one wouldn't work. Not sure if that's likely to cause any issues further down the line with domains etc?
