### ISSUE TITLE
Key concepts - Inconsistent with `Lock` and `UnlockAndRelock`

### ISSUE THREAD

**Issue by drupol** [microsoft/Office-Online-Test-Tools-and-Documentation#441]
Hello,

The [Key Concepts](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/blob/master/docs/rest/src/concepts.rst) page says: 

> All WOPI operations that modify files, such as `PutFile`, will include a lock ID as a parameter in their
> request. Usually the ID will be passed in the **X-WOPI-Lock** request header (but not always;
> `UnlockAndRelock` is an exception).

However, when we check [`UnlockAndRelock`](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/blob/master/docs/rest/src/files/UnlockAndRelock.rst), we can see that this is not true.

> X-WOPI-Lock:
>         A **string** provided by the WOPI client that the host must use to identify the new lock on
>         the file. The maximum length of a lock ID is 1024 ASCII characters. Required.

Do you think opening a PR to fix this is a good idea?

**Comment by RobRol** [comment]
Howdy drupol,

I think the confusion is that the **X-Wopi-Lock** header on the [`UnlockAndRelock`](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/blob/master/docs/rest/src/files/UnlockAndRelock.rst) request is the new lock not the old lock.

On most requests the **X-Wopi-Lock** header contains the existing lock string that the host is expected to enforce alongside the request.  The [`UnlockAndRelock`](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/blob/master/docs/rest/src/files/UnlockAndRelock.rst) request uses the **X-WOPI-OldLock** header for that string.

Best regards,
Rob Rolnick

**Comment by drupol** [comment]
Ok ok fair enough :)

Maybe this should be copy-pasted into the documentation.

Thanks for the responsiveness.
Regards.

**Comment by RobRol** [comment]
Howdy drupol,

That's reasonable.  See the [new Pull Request](https://github.com/microsoft/Office-Online-Test-Tools-and-Documentation/pull/442).

Best regards,
Rob Rolnick

**Comment by drupol** [comment]
Thanks !
