### ISSUE TITLE
"This page does not exist yet" error is displayed on https://wopi.readthedocs.io/

### ISSUE THREAD

**Issue by inhyukchoi** [microsoft/Office-Online-Test-Tools-and-Documentation#450]
"This page does not exist yet" error is displayed on https://wopi.readthedocs.io/. Has the URL for the documentation changed? Please let me know. Thanks!

**Comment by RobRol** [comment]
Howdy @inhyukchoi,

Yes, the documentation has moved to: https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/

Best,
Rob Rolnick

**Comment by inhyukchoi** [comment]
Thank you, @RobRol !
