### ISSUE TITLE
X-WOPI-RelativeUrl header is not documented

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#58]

**Comment by tylerbutler** [comment]
@chrisbro-MSFT, is this used? If so, what for?

**Comment by MarcinJuraszek** [comment]
`RelativeCobaltRequest`, to pass URL for created resource. Most likely only used by OneNote to create new sections in notebooks.

**Comment by tylerbutler** [comment]
Closing since this is only relevant to OneNote.
