### ISSUE TITLE
How should a host respond to a PutFile request in the create new case where the file will conflict with an existing file?

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#59]

**Comment by MarcinJuraszek** [comment]
What kind of conflict you have in mind? PutFile to a file which is not locked and is not zero bytes?

**Comment by tylerbutler** [comment]
I was confused. This case should never happen, since in the create new flow a host creates a file ID that they then provide to us and we PutFile to that ID, so there should never be a name conflict; or, if there is, it would be one the host deals with prior to creating the ID, not one that we deal with in PutFile.
