### ISSUE TITLE
Is the doc for X-WOPI-TimeStamp correct?

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#63]
It currently reads:

>A **64-bit integer** that represents the number of 100-nanosecond intervals that have elapsed between 12:00:00 midnight, January 1, 0001 and the time of the request.

This doesn't seem right; can you confirm, @chrisbro-MSFT?

**Comment by chrisbro-MSFT** [comment]
Yes, it is.  It is equivalent to the DateTime.UtcNow.Ticks property: https://msdn.microsoft.com/en-us/library/cc319699.aspx
