### ISSUE TITLE
JSON Schemas: Do they exist anywhere else besides [MS-WOPI]?

### ISSUE THREAD

**Issue by fabiovazquez** [Microsoft/Office-Online-Test-Tools-and-Documentation#64]
[MS-WOPI] appendix B documents JSON schemas for some Wopi Operations. Do we keep any other artifacts containing these schemas? Is there any plan to document them here?

**Comment by tylerbutler** [comment]
Good question. The JSON schemas basically just tell you:

* parameter name
* its type
* if it's required
* default value

All of these details are included in the docs for the operation, so I don't think including the raw schema adds any value. I noticed that the PutRelativeFile docs don't make it clear that the response should be JSON, so I filed #65 to track that.
