### ISSUE TITLE
Does your sample works with officeapps.live.com?

### ISSUE THREAD

**Issue by VolodymyrLychman** [Microsoft/Office-Online-Test-Tools-and-Documentation#69]
We are trying to test your sample with https://officeapps.live.com/ (https://word-edit.officeapps.live.com), but with no success. Can we use it with officeapps.live.com or are there any limitations? Some specific requirement for access_token or access_token_ttl that are not listed on wopi.readthedocs.org? 

Here is the URL and tokens that we used in the form:

    <form id="office_form" name="office_form" target="office_frame" action="https://word-view.officeapps.live.com/wv/wordviewerframe.aspx?ui=en%2DUS&rs=en%2DUS&WOPISrc=https%3a%2f%2fmywopiapp.azurewebsites.net%2fwopi%2ffiles%2ff2.docx" method="post">
        <input name="access_token" value="00000000000000000" type="hidden" />
        <input name="access_token_ttl" value="000000000000" type="hidden" />
    </form>

I have verified that sample deployed to azurewebsites.net works well and can process requests properly. I have also loged-in to my OneDrive and ShrePoint Online account before making requests.

**Comment by tylerbutler** [comment]
In order to use our service you need to be a member of the [Office 365 - Cloud Storage Partner Program](http://dev.office.com/programs/officecloudstorage). I filed a new issue (#70)  to clarify this in the docs.

**Comment by VolodymyrLychman** [comment]
Thank you for clarification, Tyler! Will Cobalt/FSSHTTP not be required for future OWA versions installed on premises also? I guess next OWA release will come with SPS 2016 https://blogs.office.com/2015/04/16/sharepoint-server-2016-update/

**Comment by jagdishkumawat30** [comment]
> We are trying to test your sample with https://officeapps.live.com/ (https://word-edit.officeapps.live.com), but with no success. Can we use it with officeapps.live.com or are there any limitations? Some specific requirement for access_token or access_token_ttl that are not listed on wopi.readthedocs.org?
> 
> Here is the URL and tokens that we used in the form:
> 
> ```
> <form id="office_form" name="office_form" target="office_frame" action="https://word-view.officeapps.live.com/wv/wordviewerframe.aspx?ui=en%2DUS&rs=en%2DUS&WOPISrc=https%3a%2f%2fmywopiapp.azurewebsites.net%2fwopi%2ffiles%2ff2.docx" method="post">
>     <input name="access_token" value="00000000000000000" type="hidden" />
>     <input name="access_token_ttl" value="000000000000" type="hidden" />
> </form>
> ```
> 
> I have verified that sample deployed to azurewebsites.net works well and can process requests properly. I have also loged-in to my OneDrive and ShrePoint Online account before making requests.

@VolodymyrLychman Can you help me in getting the ttl and access token. How did you get it?
