### ISSUE TITLE
What does FileSharingUrl do and when is it used?

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#84]

**Comment by chrisbro-MSFT** [comment]
If the user supports postmessage and the host says FileSharingPostMessage=true, we show the Share button and when the user clicks it we send the postmessage.
If the user doesn't support postmessage or the host doesn't say they do postmessage sharing, then when you click the Share button we open that URL in a new window.

If the host doesn't supply a FileSharingUrl, then the share button will not be shown either if the host doesn't send FileSharingPostMessage=true or the host/user doesn't support postmessage (browser doesn't support it, browser security settings prohibit it, etc)
