### ISSUE TITLE
Clarify how CloseUrl and CloseButtonClosesWindow are used

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#85]

**Comment by chrisbro-MSFT** [comment]
In order:
 1. if we're in Embedded mode, there is no close button.
 2. if CloseButtonClosesWindow=true, the close button is shown and it runs window.top.close.
 3. if CloseUrl has a value, the close button is shown and it navigates window.top.location to that Url
 4. else no close button.

Note that the presence/absence of the close button also affects some dialogs, like "this file is corrupt".  If we can't close the app then that dialog might have zero buttons on it, forcing the user to hit Back or something.
